[package]
name = "opcua-certificate-creator"
version = "0.7.0" # OPCUARustVersion
description = "OPC UA certificate creator"
authors = ["Adam Lock <locka99@gmail.com>"]
homepage = "https://github.com/locka99/opcua"
license = "MPL-2.0"
keywords = ["opcua","opc","ua"]
categories = ["embedded","network-programming"]
edition = "2018"

[badges]
travis-ci = { repository = "locka99/opcua" }
appveyor = { repository = "locka99/opcua" }

[dependencies]
clap = "2.33"

[dependencies.opcua-types]
path = "../../types"
version = "0.7.0" # OPCUARustVersion

[dependencies.opcua-core]
path = "../../core"
version = "0.7.0" # OPCUARustVersion
