[package]
name = "opcua-gfx-client"
version = "0.7.0" # OPCUARustVersion
authors = ["Adam Lock <locka99@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
conrod = { version = "0.61", features = ["winit", "glium"] }

[dependencies.opcua-client]
path = "../../client"
version = "0.7.0" # OPCUARustVersion

[dependencies.opcua-console-logging]
path = "../../console-logging"
version = "0.7.0" # OPCUARustVersion